security:
    encoders:
      #  Tpfnd\TpfndUserBundle\Entity\TpfndUser: plaintext
        Tpfnd\TpfndUserBundle\Entity\TpfndUser: 
           id: sha256salted_encoder 
        #Symfony\Component\Security\Core\User\User: plaintext


    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: userpass
                        roles:  'ROLE_USER'
        db_provider:
                entity:
                        class: TpfndUserBundle:TpfndUser
                        property: username
                        #property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        secured_area:
                pattern: ^/
                provider: db_provider
                anonymous: ~
                form_login:
                        login_path: /login
                        check_path: /login_check
                logout:
                    path:   /logout
                    target: /app/example
                            

    access_control:
            - { path: ^/app/example, roles: ROLE_USER }