tpfnd_sample_homepage:
    path:     /hello/{name}
    defaults: { _controller: TpfndUserBundle:Default:index }

tpfnd_home:
    path: /
    defaults: { _controller: TpfndUserBundle:TpfndHome:index }

user_register:
    path:     /register
    defaults: { _controller: TpfndUserBundle:TpfndUser:register }

user_create:
    path:     /register/create
    defaults: { _controller: TpfndUserBundle:TpfndUser:create }

login_route:
    path:     /login
    defaults: { _controller: TpfndUserBundle:Security:login }

login_check:
    path:     /login_check
    defaults: { _controller: TpfndUserBundle:Security:loginCheck }

user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: TpfndUserBundle:TpfndUser:edit }

user_update:
    path:     /user/update/{id}
    defaults: { _controller: TpfndUserBundle:TpfndUser:update }

password_change: 
    path:     /user/changepass/{id} 
    defaults: { _controller: TpfndUserBundle:TpfndUser:changePassword }

password_update:
    path:     /user/updatepass/{id}
    defaults: { _controller: TpfndUserBundle:TpfndUser:updatePassword }

password_reset:
    path:     /email/resetpass
    defaults: { _controller: TpfndUserBundle:TpfndUser:resetPassword }

process_email:
    path:     /email/processemail
    defaults: { _controller: TpfndUserBundle:TpfndUser:processEmail }

check_token:
    path: /email/check/{token}
    defaults: { _controller: TpfndUserBundle:TpfndUser:checkToken }

password_email_change:
    path:     /email/resetpass/{token}
    defaults: { _controller: TpfndUserBundle:TpfndUser:changePasswordFromEmail }

password_email_update:
    path: /email/updatepass/{token}
    defaults: { _controller: TpfndUserBundle:TpfndUser:updatePasswordFromEmail }