services:
    sha256salted_encoder:
        class: Tpfnd\TpfndUserBundle\Service\Sha256Salted

    registration_notification:
        class: Tpfnd\TpfndUserBundle\Service\RegistrationNotification
        arguments: [@twig, @mailer]
        tags:
            - { name: kernel.event_listener, event: tpfnd.events.registrationEmailNotification, method: onRegistrationEmailNotificationEvent }

    password_reset:
        class: Tpfnd\TpfndUserBundle\Service\PasswordReset
        arguments: [@twig, @mailer]
        tags:
            - { name: kernel.event_listener, event: tpfnd.events.passwordResetEmailLink, method: onPasswordResetEmailLinkEvent }

