services:
#    tpfnd_user.example:
#        class: Tpfnd\TpfndUserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    sha256salted_encoder:
        class: Tpfnd\TpfndUserBundle\Service\Sha256Salted